# Generated by Django 4.2.4 on 2023-08-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pp',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
