# Generated by Django 4.2.4 on 2023-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_pp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pp',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
