# Generated by Django 4.2.4 on 2023-08-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0003_alter_pp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pp',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
