# Generated by Django 4.2.4 on 2023-08-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0004_category_slug_alter_pp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
