# Generated by Django 4.2.4 on 2023-08-29 09:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0007_alter_pp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pp',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
