# Generated by Django 4.2.4 on 2023-08-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0009_pp_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pp',
            name='category',
        ),
        migrations.AddField(
            model_name='pp',
            name='categories',
            field=models.ManyToManyField(to='pp.category'),
        ),
    ]
